### ISSUE TITLE
MongoDB Update + Schema

### ISSUE THREAD

**Issue by Lewdcario** [Progressive-Victory/crm-bot#20]
* Check if the server database can be upgraded
* Upgrade the client database
* Document required MongoDB server and client versions

**Comment by bowenjw** [comment]
may be worth looking at switching to [mongoosejs](https://mongoosejs.com/) at the same time
here is a comparison written by MongoDB Developer blog https://www.mongodb.com/developer/languages/javascript/mongoose-versus-nodejs-driver/
