### ISSUE TITLE
Meeting Agendas

### ISSUE THREAD

**Issue by andpeterson** [Progressive-Victory/crm-bot#38]
Create Meetings and add to the agenda with the PV bot so that way you can remember things to bring up on future meeting agendas
Features:
- Creates a meeting
- Can add/remove attendees users or roles to the meeting
- Can add agenda item reminders to the agenda
- Promote attendee to organizer of the event?
- Can print out meeting details without clearing anything
- Can wipe out the agenda item reminders (only the original creator, or an organizer can)
- Can send reminders about the meeting to attenders
- Can add a location to the meeting
    - Can rename an Organizing VC at meeting start and can print the agenda in the VC chat at the start of the meeting
Sends agenda to the creator/organizers in DMs at the start of the meeting

Commands should be accessible in the server or in DMs if possible
Users should only see meetings that they have been invited to

Commands:
/meeting create {title} {time} {recurring period}
/meeting attendee add {title} {user}
/meeting attendee promote {title} {user}
/meeting agenda add {title}
/meeting details {title}
/meeting reminder set {title}
/meeting agenda clear {title}
/meeting reminder send {title}
/meeting location set {VC or string}

**Comment by Lewdcario** [comment]
We use mongoDB currently, but heres the outline i expect for this:

Table:
```
title: string
attendees: string[] (discord snowflake, which is just a kind of string)
createdAt: timestamp
updatedAt: timestamp
details: text
reminders: [{ title: string, time: timestamp }]
agenda: string[]
location: string
```

I suggest adding database methods that accomplishes basic interaction with each table. For example, we may want a function like this, if I recall correctly:

```static setTitle(meetingID: number, title: string)
return Database.db.collection('meetings').update({
meetingID,
title
}, {
upsert: true
})
```
Source: https://www.mongodb.com/docs/manual/reference/method/db.collection.update/
