### ISSUE TITLE
Notify Team leads

### ISSUE THREAD

**Issue by Lewdcario** [Progressive-Victory/crm-bot#69]
When someone selects a role for that team lead, the bot could DM them notifying them of this. This can help prompt them to engage with that user. This will require us to match roles to users (can be more than one lead, so use an array)

**Comment by bowenjw** [comment]
Would it be better to use private thread. For example, the selected member has their DMs restricted

**Comment by Lewdcario** [comment]
There can be a fallback to post in a specified channel defined in the environment, and then it can ping said lead(s), but DM is ideal for the preference
