### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by Lewdcario** [Progressive-Victory/crm-bot#80]
![image](https://github.com/Progressive-Victory/crm-bot/assets/11844002/5d4ac61f-a300-427c-b69e-c5ed74272a1b)
This error occurs when the database url isn't filled. We need to throw with a better message before that happens - also take the opportunity to test others for other vague errors

**Comment by bowenjw** [comment]
the solutions is to add a try block to [line 80 in ./src/index.ts](https://github.com/Progressive-Victory/crm-bot/blob/5d8b79c2cd5de2a05ada5dc47f3b2adca688fc72/src/index.ts#L54C3-L54C30)
